<form class="form" id="my-form" method="post" data-mage-init='{"validation":{"rules": {"field-4": {"required":true, "letters-only":true}}}}'>
    <fieldset class="fieldset">
        <div class="field name required">
            <label class="label" for="field-1"><span>Validaçao de URL (usando data-validate)</span></label>
            <div class="control">
                <input name="field-1" id="field-1" title="Field 1" value=""  class="input-text" type="text" data-validate='{"required":true, "url": true}'/>
            </div>
        </div>
        <div class="field name required">
            <label class="label" for="field-2"><span>Validaçao de Email (usando atributo)</span></label>
            <div class="control">
                <input name="field-2" id="field-2" title="Field 2" value="" class="input-text" type="text" required="true" validate-email="true"/>
            </div>
        </div>
        <div class="field name required">
            <label class="label" for="field-3"><span>Validaçao de Numero Obrigatorio (usando classname)</span></label>
            <div class="control">
                <input name="field-3" id="field-3" title="Field 3" value="" type="text" class="input-text required-number "/>
            </div>
        </div>
        <div class="field name required">
            <label class="label" for="field-4"><span>Validaçao Apenas Letras (usando data-mage-init)</span></label>
            <div class="control">
                <input name="field-4" id="field-4" title="Field 4" value="" class="input-text" type="text"/>
            </div>
        </div>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" title="Submit" class="action submit primary">
                <span>Submit</span>
            </button>
        </div>
    </div>
</form>
